# Generated by Django 4.2.7 on 2025-11-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slides_content',
            field=models.JSONField(blank=True, default=dict, help_text='Structured content for slides'),
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='learning.module')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='learning.concept')),
                ('related_concepts', models.ManyToManyField(blank=True, to='learning.concept')),
            ],
            options={
                'db_table': 'concepts',
                'ordering': ['title'],
            },
        ),
    ]
