# Generated by Django 4.2.7 on 2025-11-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_content_slides_content_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata for content types'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text/Article'), ('video', 'Video'), ('mental_model', 'Mental Model'), ('code', 'Code Exercise'), ('quiz', 'Quiz'), ('project', 'Project'), ('interactive', 'Interactive Demo')], max_length=20),
        ),
    ]
