# Generated by Django 4.2.7 on 2025-11-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_content_metadata_alter_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='mental_model_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='mental_model_image',
            field=models.URLField(blank=True, help_text='URL for mental model diagram', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='mental_model_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='video_summary',
            field=models.TextField(blank=True, help_text='Summary of the video content', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AlterField(
            model_name='content',
            name='text_content',
            field=models.TextField(blank=True, help_text='Main textual explanation', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or video URL', null=True),
        ),
    ]
