# Generated by Django 4.2.7 on 2025-11-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_content_mental_model_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='mental_model_description',
            new_name='concept_graph_description',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='mental_model_title',
            new_name='concept_graph_title',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='mental_model_image',
            new_name='concept_graph_image',
        ),
        migrations.AlterField(
            model_name='content',
            name='concept_graph_image',
            field=models.URLField(blank=True, help_text='URL for concept graph diagram', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text/Article'), ('video', 'Video'), ('concept_graph', 'Concept Graph'), ('code', 'Code Exercise'), ('quiz', 'Quiz'), ('project', 'Project'), ('interactive', 'Interactive Demo')], max_length=20),
        ),
    ]
