# Generated by Django 4.2.7 on 2025-11-18 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('interests', models.JSONField(default=list, help_text='List of AI topics of interest')),
                ('learning_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('preferred_learning_style', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('total_time_spent', models.IntegerField(default=0, help_text='Total learning time in minutes')),
                ('current_streak', models.IntegerField(default=0, help_text='Current learning streak in days')),
                ('longest_streak', models.IntegerField(default=0, help_text='Longest learning streak in days')),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('daily_goal_minutes', models.IntegerField(default=30)),
                ('email_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('view', 'View Content'), ('complete', 'Complete Content'), ('like', 'Like Content'), ('bookmark', 'Bookmark Content'), ('chat', 'Chat Interaction'), ('search', 'Search Query')], max_length=20)),
                ('content_type', models.CharField(help_text='Type of content interacted with', max_length=100)),
                ('content_id', models.IntegerField(help_text='ID of the content')),
                ('metadata', models.JSONField(default=dict, help_text='Additional activity metadata')),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='user_activi_user_id_6bb195_idx'), models.Index(fields=['activity_type', '-timestamp'], name='user_activi_activit_b512c7_idx')],
            },
        ),
    ]
