# Generated by Django 4.2.7 on 2025-11-18 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('complete', 'Complete'), ('like', 'Like'), ('dislike', 'Dislike'), ('bookmark', 'Bookmark'), ('share', 'Share'), ('skip', 'Skip')], max_length=20)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('completion_percentage', models.FloatField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, help_text='User rating: 1-5', null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('referrer', models.CharField(blank=True, help_text='How user found this content', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='learning.content')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='learning.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'interaction_type', '-created_at'], name='user_intera_user_id_0e0417_idx'), models.Index(fields=['learning_path', '-created_at'], name='user_intera_learnin_bcc4ef_idx'), models.Index(fields=['content', '-created_at'], name='user_intera_content_aa9436_idx')],
            },
        ),
        migrations.CreateModel(
            name='SimilarityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Cosine similarity or other metric')),
                ('score_type', models.CharField(default='embedding', help_text='Type of similarity: embedding, collaborative, content-based', max_length=30)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('learning_path_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_first', to='learning.learningpath')),
                ('learning_path_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_as_second', to='learning.learningpath')),
            ],
            options={
                'db_table': 'similarity_scores',
                'indexes': [models.Index(fields=['learning_path_1', '-similarity_score'], name='similarity__learnin_14facb_idx')],
                'unique_together': {('learning_path_1', 'learning_path_2', 'score_type')},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('next_content', 'Next Content'), ('similar_path', 'Similar Learning Path'), ('collaborative', 'Users Also Learned'), ('skill_gap', 'Fill Knowledge Gap'), ('trending', 'Trending Content')], max_length=30)),
                ('score', models.FloatField(help_text='Recommendation confidence score')),
                ('reasoning', models.TextField(help_text='Why this is recommended')),
                ('metadata', models.JSONField(default=dict, help_text='Additional recommendation data')),
                ('viewed', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When recommendation becomes stale', null=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.content')),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.learningpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recommendat_user_id_e124dd_idx'), models.Index(fields=['recommendation_type', '-score'], name='recommendat_recomme_dac802_idx')],
            },
        ),
    ]
